src/main/java/pl/kmo2008/oskmanager/entity/Car.java
package pl.kmo2008.oskmanager.entity;

import lombok.Data;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.Set;

@Entity
@Data
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "car_id")
    int id;

    @Column(name = "mark")
    String mark;

    @Column(name = "model")
    String model;

    @Column(name = "plate")
    String plate;

    @Column(name = "productionYear")
    Integer productionYear;

    @Column(name = "endOfReview")
    LocalDate endOfReview;

    @Column(name = "endOfInsurance")
    LocalDate endOfInsurance;

    @ManyToMany
    @JoinTable(name = "car_categories", joinColumns = @JoinColumn(name = "car_id"), inverseJoinColumns = @JoinColumn(name = "category_id"))
    @OrderBy("name")
    private Set<Category> categories;
}

src/main/java/pl/kmo2008/oskmanager/entity/Course.java
package pl.kmo2008.oskmanager.entity;

import lombok.Data;
import pl.kmo2008.oskmanager.entity.extensions.Client;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;

@Entity
@Data
public class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id;

    @Column(name = "courseNumber")
    String courseNumber;

    @Column(name = "startDate")
    LocalDate startDate;

    @Column(name = "endDate")
    LocalDate endDate;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    Category category;

    @Column(name = "price")
    double price;

    @ManyToMany
    @JoinTable(name = "curse_client", joinColumns = @JoinColumn(name = "curse_id"), inverseJoinColumns = @JoinColumn(name = "client_id"))
    private List<Client> clients;
}

src/main/java/pl/kmo2008/oskmanager/entity/Transaction.java
package pl.kmo2008.oskmanager.entity;

import lombok.Data;
import pl.kmo2008.oskmanager.entity.extensions.Client;

import javax.persistence.*;
import java.time.LocalDate;

@Entity
@Data
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id")
    Course course;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    Client client;

    @Column(name = "date")
    LocalDate date;

    @Column(name = "value")
    Double value;
}

src/main/java/pl/kmo2008/oskmanager/entity/User.java
package pl.kmo2008.oskmanager.entity;

import lombok.Data;
import org.hibernate.validator.constraints.Length;
import pl.kmo2008.oskmanager.entity.enums.Document;
import pl.kmo2008.oskmanager.entity.enums.Sex;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import java.time.LocalDateTime;
import java.util.Set;

@Data
@Entity
@Table(name = "user")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "user_id")
    private int id;

    @Column(name = "email")
    @Email(message = "*Please provide a valid Email")
    @NotEmpty(message = "*Please provide an email")
    private String email;

    @Column(name = "password")
    @Length(min = 5, message = "*Your password must have at least 5 characters")
    @NotEmpty(message = "*Please provide your password")
    private String password;

    @Column(name = "name")
    @NotEmpty(message = "*Please provide your name")
    private String name;

    @Column(name = "secondName")
    private String secondName;

    @Column(name = "last_name")
    @NotEmpty(message = "*Please provide your last name")
    private String lastName;

    @Column(name = "active")
    private int active;

    @ManyToMany
    @JoinTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> roles;

    @Column(name = "sex")
    private Sex sex;

    @Column(name = "street")
    private String street;

    @Column(name = "houseNumber")
    private String houseNumber;

    @Column(name = "apartmentNumber")
    private String apartmentNumber;

    @Column(name = "postCode")
    private String postCode;

    @Column(name = "City")
    private String city;

    @Column(name = "pesel")
    private String pesel;

    @Column(name = "document")
    private Document document;

    @Column(name = "documentNumber")
    private String documentNumber;

    @Column(name = "phone")
    private String phone;

    @Column(name = "expirationDate")
    private LocalDateTime expirationDate;

    @Column(name = "passwordExpiration")
    private LocalDateTime passwordExpiration;

    @Column(name = "defaultPassword")
    private String defaultPassword;


    public String getFullName() {
        if (this.secondName != null)
            return this.name + " " + this.secondName + " " + this.lastName;
        else
            return this.name + " " + this.lastName;
    }

}

src/main/java/pl/kmo2008/oskmanager/entity/enums/RideType.java
package pl.kmo2008.oskmanager.entity.enums;

public enum RideType {
    NORMAL, ADDITIONAL
}

src/main/java/pl/kmo2008/oskmanager/controller/CarController.java
package pl.kmo2008.oskmanager.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import pl.kmo2008.oskmanager.service.AlertService;
import pl.kmo2008.oskmanager.service.CarService;
import pl.kmo2008.oskmanager.service.CategoryService;
import pl.kmo2008.oskmanager.service.ModelService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@Controller
public class CarController {

    @Autowired
    ModelService modelService;

    @Autowired
    CarService carService;

    @Autowired
    CategoryService categoryService;

    @Autowired
    AlertService alertService;

    @RequestMapping(path = "/car/list", method = RequestMethod.GET)
    public ModelAndView instructorList() {
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("cars", carService.findAll());
        modelAndView.addObject("categories", categoryService.findAll());
        modelAndView.setViewName("car");
        return modelAndView;
    }

    @PostMapping(path = "/car/add")
    public String add(HttpServletRequest request, HttpServletResponse response){
        carService.add(request);
        return "redirect:/car/list";
    }

    @PostMapping(path = "/car/edit/{id}")
    public String edit(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response){
        carService.edit(id, request);
        return "redirect:/car/list";
    }

    @GetMapping(path = "/car/delete/{id}")
    public String delete(@PathVariable("id") Integer id){
        alertService.deleteByCarId(id);
        carService.delete(id);
        return "redirect:/car/list";
    }
}

src/main/java/pl/kmo2008/oskmanager/controller/ClientController.java
package pl.kmo2008.oskmanager.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import pl.kmo2008.oskmanager.service.CategoryService;
import pl.kmo2008.oskmanager.service.ClientService;
import pl.kmo2008.oskmanager.service.ModelService;
import pl.kmo2008.oskmanager.service.UserService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@Controller
public class ClientController {

    @Autowired
    UserService userService;

    @Autowired
    ModelService modelService;

    @Autowired
    ClientService clientService;

    @Autowired
    CategoryService categoryService;

    @RequestMapping(value="/client/list", method = RequestMethod.GET)
    public ModelAndView home(){
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("clients", clientService.findAll());
        modelAndView.setViewName("client");
        return modelAndView;
    }

    @GetMapping(path = "/client/edit/{id}")
    public ModelAndView instructorEdit(@PathVariable("id") Integer id) {
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("client", clientService.findById(id));
        modelAndView.addObject("categories", categoryService.findAll());
        modelAndView.setViewName("clientEdit");
        return modelAndView;
    }

    @GetMapping(path = "/client/active/{id}")
    public String active(@PathVariable("id") Integer id){
        clientService.active(clientService.findById(id));
        return "redirect:/client/list";
    }

    @PostMapping(path = "/client/add")
    public String clientEdit(HttpServletRequest request, HttpServletResponse response) {
        clientService.add(request);
        return "redirect:/client/list";
    }

    @PostMapping(path = "/client/edit/{id}")
    public String clientEdit(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response) {
        clientService.edit(request, id);
        return "redirect:/client/edit/"+id;
    }

    @PostMapping(path = "/client/addInstructor/{courseId}/{clientId}")
    public String clientAddInstructor(@PathVariable Integer courseId, @PathVariable Integer clientId, HttpServletRequest request){
        clientService.addInstructor(courseId, clientId, request);
        return "redirect:/course/edit/" + courseId;
    }

    @GetMapping(path = "/client/delete/{id}")
    public String delete(@PathVariable("id") Integer id){
        clientService.delete(id);
        return "redirect:/client/list";
    }
}

src/main/java/pl/kmo2008/oskmanager/controller/CourseController.java
package pl.kmo2008.oskmanager.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;
import pl.kmo2008.oskmanager.entity.Course;
import pl.kmo2008.oskmanager.repository.ClientInstructorRepostiory;
import pl.kmo2008.oskmanager.service.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@Controller
public class CourseController {

    @Autowired
    ModelService modelService;

    @Autowired
    CourseService courseService;

    @Autowired
    CategoryService categoryService;

    @Autowired
    ClientService clientService;

    @Autowired
    InstructorService instructorService;

    @Autowired
    ClientInstructorRepostiory clientInstructorRepostiory;

    @GetMapping(path = "/course/list")
    public ModelAndView home() {
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("course", courseService.findAll());
        modelAndView.setViewName("course");
        return modelAndView;
    }

    @GetMapping(path = "/course/edit/{id}")
    public ModelAndView instructorEdit(@PathVariable("id") Integer id) {
        ModelAndView modelAndView = modelService.getNew();
        Course course;
        if (id == -1) {
            course = new Course();
            courseService.save(course);
        } else course = courseService.findById(id);
        modelAndView.addObject("course", course);
        modelAndView.addObject("categories", categoryService.findAll());
        modelAndView.addObject("clients", clientService.findAll());
        modelAndView.addObject("instructors", instructorService.findAll());
        modelAndView.addObject("clientInstructors", clientInstructorRepostiory.findAllByCourse(course));
        modelAndView.setViewName("courseEdit");
        return modelAndView;
    }

    @PostMapping(path = "/course/edit/{id}")
    public String courseEdit(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response) {
        courseService.edit(request, id);
        return "redirect:/course/edit/" + id;
    }

    @PostMapping(path = "/course/addClient/{id}")
    public String courseAddClient(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response) {
        courseService.addClient(request, id);
        return "redirect:/course/edit/" + id;
    }

    @GetMapping(path = "/course/delete/{id}")
    public String delete(@PathVariable("id") Integer id) {
        courseService.delete(id);
        return "redirect:/course/list";
    }


}

src/main/java/pl/kmo2008/oskmanager/controller/InstructorController.java
package pl.kmo2008.oskmanager.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import pl.kmo2008.oskmanager.entity.Ride;
import pl.kmo2008.oskmanager.entity.enums.RideType;
import pl.kmo2008.oskmanager.entity.extensions.Instructor;
import pl.kmo2008.oskmanager.service.CategoryService;
import pl.kmo2008.oskmanager.service.InstructorService;
import pl.kmo2008.oskmanager.service.ModelService;
import pl.kmo2008.oskmanager.service.RideService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Controller
public class InstructorController {

    @Autowired
    ModelService modelService;

    @Autowired
    InstructorService instructorService;

    @Autowired
    CategoryService categoryService;

    @Autowired
    RideService rideService;

    @RequestMapping(path = "/instructor/list", method = RequestMethod.GET)
    public ModelAndView instructorList() {
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("instructors", instructorService.findAll());
        modelAndView.addObject("categories", categoryService.findAll());
        modelAndView.setViewName("instructor");
        return modelAndView;
    }

    @PostMapping(path = "/instructor/add")
    public String instructorAdd(HttpServletRequest request, HttpServletResponse response) {
        instructorService.add(request);
        return "redirect:/instructor/list";
    }

    @GetMapping(path = "/instructor/edit/{id}")
    public ModelAndView instructorEdit(@PathVariable("id") Integer id) {
        ModelAndView modelAndView = modelService.getNew();
        modelAndView.addObject("instructor", instructorService.findById(id));
        modelAndView.addObject("categories", categoryService.findAll());

        List<Ride> rides = rideService.findAllByInstructorId(id).stream().sorted(Comparator.comparing(Ride::getDate)).collect(Collectors.toList());
        List<Ride> rider = rides.stream()
                .filter(ride ->
                        ride.getDate().getMonthValue() == LocalDate.now().getMonthValue() || ride.getDate().getMonthValue() == LocalDate.now().minusMonths(1).getMonthValue() || ride.getDate().getMonthValue() == LocalDate.now().minusMonths(2).getMonthValue()
                ).collect(Collectors.toList());

        HashMap<Integer, Double> payment = new HashMap<>();


        rider.forEach(ride -> {
            payment.put(ride.getMotnh(), getPayment(ride.getMotnh(), ride.getDuration(), ride.getRideType(),instructorService.findById(id), payment));
        });



        modelAndView.addObject("rides", payment);
        modelAndView.setViewName("instructorEdit");
        return modelAndView;
    }

    @PostMapping(path = "/instructor/edit/{id}/name")
    public String instructorEditName(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response) {
        instructorService.editName(request, id);
        return "redirect:/instructor/edit/" + id;
    }

    @PostMapping(path = "/instructor/edit/{id}/all")
    public String instructorEditAll(@PathVariable("id") Integer id, HttpServletRequest request, HttpServletResponse response) {
        instructorService.edit(request, id);
        return "redirect:/instructor/edit/" + id;
    }

    @GetMapping(path = "/instructor/delete/{id}")
    public String instructorDelete(@PathVariable("id") Integer id) {
        instructorService.delete(id);
        return "redirect:/instructor/list";
    }

    @GetMapping(path = "/instructor/active/{id}")
    public String active(@PathVariable("id") Integer id) {
        instructorService.active(instructorService.findById(id));
        return "redirect:/instructor/list";
    }

    private double getPayment(int month, double duration, RideType type, Instructor instructor, HashMap payment){
        double old;
        if(payment.get(month) == null){
            old = 0.0;
        }
        else old = (double) payment.get(month);
        if(type == RideType.NORMAL)
            return instructor.getNormalPayment() * duration + old;
        else return instructor.getAdditionalPayment() * duration + old;
    }
}

src/main/java/pl/kmo2008/oskmanager/controller/LoginController.java
package pl.kmo2008.oskmanager.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class LoginController {


    @RequestMapping(value={"/", "/login"}, method = RequestMethod.GET)
    public ModelAndView login(){
        ModelAndView modelAndView = new ModelAndView();
        modelAndView.setViewName("login");
        return modelAndView;
    }





}

src/main/webapp/WEB-INF/views/accessDenied.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Brak dostępu - OSKManager</title>
    <%@include file="static/heads.jsp"%>
</head>

<body>
<!-- preloader area start -->
<div id="preloader">
    <div class="loader"></div>
</div>
<!-- preloader area end -->
<!-- page container area start -->
<div class="page-container">
    <%@include file="static/menu.jsp" %>
    <!-- main content area start -->
    <div class="main-content">
        <!-- header area start -->
        <div class="header-area">
            <div class="row align-items-center">
                <!-- nav and search button -->
                <div class="col-md-6 col-sm-8 clearfix">
                    <div class="nav-btn pull-left">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <!-- profile info & task notification -->
            </div>
        </div>
        <!-- header area end -->
        <!-- page title area start -->
        <div class="page-title-area">
            <div class="row align-items-center">
                <div class="col-sm-6">
                    <div class="breadcrumbs-area clearfix">
                        <h4 class="page-title pull-left">Brak dostępu</h4>
                        <ul class="breadcrumbs pull-left">
                            <li><a href="${pageContext.request.contextPath}/dashboard">Strona Główna</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 clearfix">
                    <div class="user-profile pull-right">
                        <%@ page import="pl.kmo2008.oskmanager.entity.enums.Sex" %>
                        <c:choose>
                            <c:when test="${user.sex == Sex.MAN}">
                                <img class="avatar user-thumb" src="${pageContext.request.contextPath}/static/images/author/avatar_man.png" alt="avatar">
                            </c:when>
                            <c:otherwise>
                                <img class="avatar user-thumb" src="${pageContext.request.contextPath}/static/images/author/avatar_woman.png" alt="avatar">
                            </c:otherwise>
                        </c:choose>
                        <h4 class="user-name">${user.fullName}</h4>
                    </div>
                </div>
            </div>
        </div>
        <!-- page title area end -->
        <div class="main-content-inner">
            <span class="text-center"><h1>Nie masz uprawnień do przeglądania tej strony.</h1></span>
        </div>
    </div>
    <!-- main content area end -->
    <!-- footer area start-->
    <footer>
        <div class="footer-area">
            <p>© Copyright 2018. All right reserved. Template by <a href="https://colorlib.com/wp/">Colorlib</a>.</p>
        </div>
    </footer>
    <!-- footer area end-->
</div>
<!-- page container area end -->
<%@include file="static/footer.jsp"%>
</body>

</html>

src/main/webapp/WEB-INF/views/changePassword.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Dashboard - OSKManager</title>
    <%@include file="static/heads.jsp" %>
</head>

<body>
<!-- preloader area start -->
<div id="preloader">
    <div class="loader"></div>
</div>
<!-- preloader area end -->
<!-- page container area start -->
<div class="page-container">
    <%@include file="static/menu.jsp" %>
    <!-- main content area start -->
    <div class="main-content">
        <!-- header area start -->
        <div class="header-area">
            <div class="row align-items-center">
                <!-- nav and search button -->
                <div class="col-md-6 col-sm-8 clearfix">
                    <div class="nav-btn pull-left">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <!-- profile info & task notification -->
            </div>
        </div>
        <!-- header area end -->
        <!-- page title area start -->
        <div class="page-title-area">
            <div class="row align-items-center">
                <div class="col-sm-6">
                    <div class="breadcrumbs-area clearfix">
                        <h4 class="page-title pull-left">Strona Główna</h4>
                        <ul class="breadcrumbs pull-left">
                            <li><a href="${pageContext.request.contextPath}/dashboard">Strona Główna</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 clearfix">
                    <div class="user-profile pull-right">
                        <%@ page import="pl.kmo2008.oskmanager.entity.enums.Sex" %>
                        <c:choose>
                            <c:when test="${user.sex == Sex.MAN}">
                                <img class="avatar user-thumb"
                                     src="${pageContext.request.contextPath}/static/images/author/avatar_man.png"
                                     alt="avatar">
                            </c:when>
                            <c:otherwise>
                                <img class="avatar user-thumb"
                                     src="${pageContext.request.contextPath}/static/images/author/avatar_woman.png"
                                     alt="avatar">
                            </c:otherwise>
                        </c:choose>
                        <h4 class="user-name">${user.fullName}</h4>
                    </div>
                </div>
            </div>
        </div>
        <!-- page title area end -->
        <div class="main-content-inner">
            <c:if test="${result == 1}">
                <div class="alert alert-danger">
                    <h3>Hasła nie są takie same.</h3>
                </div>
            </c:if>
            <c:if test="${result == 0}">
                <div class="alert alert-success">
                    <h3>Hasło zmienione.</h3>
                </div>
            </c:if>
            <form action="${pageContext.request.contextPath}/user/changePassword"
                  method="post">
                <input type="hidden"
                       name="${_csrf.parameterName}"
                       value="${_csrf.token}"/>

                    <label for="password">Nowe hasło: </label><input class="form-control input-rounded" type="password" id="password" name="password">

                    <label for="password2">Powtórz hasło: </label><input class="form-control input-rounded" type="password" id="password2" name="password2">
                    <button type="button"
                            class="btn btn-secondary"
                            data-dismiss="modal">
                        Zamknij
                    </button>
                    <button type="submit"
                            class="btn btn-primary">
                        Zapisz
                    </button>
            </form>
        </div>
    </div>
    <!-- main content area end -->
    <!-- footer area start-->
    <footer>
        <div class="footer-area">
            <p>© Copyright 2018. All right reserved. Template by <a href="https://colorlib.com/wp/">Colorlib</a>.</p>
        </div>
    </footer>
    <!-- footer area end-->
</div>
<!-- page container area end -->
<%@include file="static/footer.jsp" %>
</body>

</html>

src/main/webapp/WEB-INF/views/errorPage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<head>
    <title>Home</title>
</head>
<body>
<h1>${errorMsg}</h1>
</body>
</html>